apiVersion: v1
kind: Service
metadata:
  name: {{ include "lemp.fullname" . }}
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
  {{- range $ip := .Values.service.externalIPs }}
    - {{ $ip }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lemp.selectorLabels" . | nindent 4 }}